package com.myapplication.common.secure

import java.io.File
import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Conformance of the Kotlin TSE2 implementation against `secure/vectors.json`,
 * the vector file generated by the Python reference (`secure/gen_vectors.py`,
 * which is itself checked against RFC 9180 Appendix A.1). Every vector fixes
 * skR, skE, ts, rid and the plaintext, so the envelope bytes and the exported
 * response key must match byte for byte — this is what proves the browser,
 * Python and Kotlin clients seal the same thing.
 *
 * The file lives in the parent repository (this module is a submodule). When it
 * is absent (standalone checkout) the test reports that and passes vacuously;
 * set TSE2_VECTORS=/path/to/vectors.json to point at a copy.
 */
class Tse2VectorsTest {

    private fun vectorsFile(): File? {
        System.getenv("TSE2_VECTORS")?.let { p -> File(p).takeIf { it.isFile }?.let { return it } }
        var dir: File? = File(".").absoluteFile
        repeat(6) {
            val f = File(dir, "secure/vectors.json")
            if (f.isFile) return f
            dir = dir?.parentFile
        }
        return null
    }

    private fun hex(s: String): ByteArray = ByteArray(s.length / 2) { i -> s.substring(2 * i, 2 * i + 2).toInt(16).toByte() }
    private fun ByteArray.hex(): String = joinToString("") { "%02x".format(it) }

    /**
     * Minimal JSON reader for the vector file (no kotlinx-serialization on the
     * test path). Hand-rolled rather than a regex: the hex fields are thousands
     * of characters long and java.util.regex overflows its stack on them.
     */
    private fun field(obj: String, key: String): String {
        val k = "\"" + key + "\""
        var i = obj.indexOf(k)
        require(i >= 0) { "field $key missing" }
        i += k.length
        while (i < obj.length && obj[i] != ':') i++
        i++
        while (i < obj.length && obj[i].isWhitespace()) i++
        return if (obj[i] == '"') {
            val sb = StringBuilder()
            i++
            while (obj[i] != '"') {
                if (obj[i] == '\\') { sb.append(obj[i]); i++ }
                sb.append(obj[i]); i++
            }
            sb.toString()
        } else {
            val start = i
            while (i < obj.length && (obj[i].isDigit() || obj[i] == '-' || obj[i] == '.')) i++
            obj.substring(start, i)
        }
    }

    private fun tse2Objects(json: String): List<String> {
        val start = json.indexOf("\"tse2\"")
        require(start >= 0) { "no tse2 section" }
        val arrStart = json.indexOf('[', start)
        val out = mutableListOf<String>()
        var depth = 0
        var objStart = -1
        var i = arrStart + 1
        while (i < json.length) {
            when (json[i]) {
                '{' -> { if (depth == 0) objStart = i; depth++ }
                '}' -> { depth--; if (depth == 0) out += json.substring(objStart, i + 1) }
                ']' -> if (depth == 0) return out
                '"' -> { i++; while (json[i] != '"') { if (json[i] == '\\') i++; i++ } }
            }
            i++
        }
        return out
    }

    @Test
    fun envelopesMatchThePythonReferenceByteForByte() {
        val f = vectorsFile()
        if (f == null) {
            println("Tse2VectorsTest: secure/vectors.json not found (standalone checkout) — set TSE2_VECTORS to run")
            return
        }
        val json = f.readText()
        val vectors = tse2Objects(json)
        assertTrue(vectors.size >= 3, "expected >= 3 TSE2 vectors, got ${vectors.size}")
        val hpke = platformHpke()
        for (v in vectors) {
            val name = field(v, "name")
            val pkR = hex(field(v, "pkR"))
            val kid = hex(field(v, "kid"))
            val skE = hex(field(v, "skE"))
            val route = field(v, "route")
            val ts = field(v, "ts").toLong()
            val rid = hex(field(v, "rid"))
            val plaintext = hex(field(v, "plaintext"))
            assertContentEquals(kid, Tse2.kidOf(pkR), "$name: kid")

            val sealed = Tse2.sealRequest(hpke, pkR, kid, route, plaintext, ts, rid, deterministicEphemeralPrivateKey = skE)
            assertEquals(field(v, "envelope"), sealed.envelope.hex(), "$name: envelope")
            assertEquals(field(v, "key_resp"), sealed.state.responseKey.hex(), "$name: exported response key")

            // the sealed reply in the vector opens with that key and yields the JSON
            val respObj = v.substring(v.indexOf("\"response\"") + 10)
            val responseHex = field(respObj, "response")
            val expectedJson = field(respObj, "json").replace("\\\"", "\"")
            val opened = Tse2.openResponse(hpke, sealed.state, hex(responseHex))
            assertEquals(expectedJson, String(opened, Charsets.UTF_8), "$name: opened reply")

            // any bit flipped in the reply is rejected, never rendered
            val bad = hex(responseHex).also { it[it.size - 1] = (it[it.size - 1].toInt() xor 1).toByte() }
            assertFailsWith<Tse2Exception> { Tse2.openResponse(hpke, sealed.state, bad) }
        }
    }

    @Test
    fun headerLayoutAndKidBinding() {
        val hpke = platformHpke()
        val skR = ByteArray(32) { (it + 1).toByte() }
        // derive a valid pkR through HPKE's own key deserialisation path is not exposed; use a vector's pkR
        val f = vectorsFile() ?: return
        val v = tse2Objects(f.readText()).first()
        val pkR = hex(field(v, "pkR"))
        val kid = Tse2.kidOf(pkR)
        val sealed = Tse2.sealRequest(hpke, pkR, kid, "/analyze", byteArrayOf(1, 2, 3))
        val h = Tse2.parseRequestHeader(sealed.envelope)
        assertContentEquals(kid, h.kid)
        assertEquals(32, h.enc.size)
        assertEquals(3 + Tse2.GCM_TAG_LEN, h.ciphertext.size)
        assertTrue(h.tsUnixSeconds > 1_600_000_000L)
        // a kid that is not SHA-256(pkR)[0:8] must be refused before any crypto
        assertFailsWith<IllegalArgumentException> { Tse2.sealRequest(hpke, pkR, ByteArray(8), "/analyze", byteArrayOf(1)) }
        assertFailsWith<IllegalArgumentException> { Tse2.sealRequest(hpke, pkR, kid, "analyze", byteArrayOf(1)) }
        assertFailsWith<IllegalArgumentException> { Tse2.sealRequest(hpke, pkR, kid, "/analyze?x=1", byteArrayOf(1)) }
        assertTrue(skR.isNotEmpty())
    }
}
